# Generated by Django 2.0 on 2017-12-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.DateTimeField(verbose_name='date due/exam date')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='example@example.com', max_length=256),
            preserve_default=False,
        ),
    ]
