# Generated by Django 2.0 on 2017-12-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='week',
            field=models.IntegerField(blank=True, null=True, verbose_name='week'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='date',
            field=models.DateTimeField(blank=True, verbose_name='date due/exam date'),
        ),
    ]
