# Generated by Django 2.0 on 2017-12-12 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20171212_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='unit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='planner.Unit'),
            preserve_default=False,
        ),
    ]
